version: '3'
services:
  nginx:
    image: "${DOCKERHUB_USERNAME}/my-nginx-site:latest"
    container_name: my-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123 # Change this to your preferred password
    volumes:
      - grafana-storage:/var/lib/grafana

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:edge
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command: [
      "-nginx.scrape-uri", "http://nginx:80/stub_status"
    ]

volumes:
  grafana-storage:
