name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test network connectivity to router
        run: |
          echo "Pinging the router..."
          ping -c 4 ${{ secrets.ROUTER_PUBLIC_IP }}

      - name: Check if port is open on router
        run: |
          nc -zv ${{ secrets.ROUTER_PUBLIC_IP }} ${{ secrets.ROUTER_PORT }}

      - name: Add router public IP address to known hosts
        run: | 
          ssh-keyscan -p ${{ secrets.ROUTER_PORT }} ${{ secrets.ROUTER_PUBLIC_IP }} >> ~/.ssh/known_hosts




