name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Tunnel
        run: |
          echo "Setting up SSH Tunnel..."
          ssh -N -L 2222:${{ secrets.ROUTER_PUBLIC_IP }}:22 -p ${{ secrets.ROUTER_PORT }} ${{ secrets.RPI5_USERNAME }}@${{ secrets.ROUTER_PUBLIC_IP }} &
          sleep 5  # Wait for the tunnel to establish

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to localhost through the tunnel..."
          ssh -o StrictHostKeyChecking=no -p 2222 localhost "echo Connection Successful"

      # - name: Create Ansible Inventory
      #   run: |
      #     echo "[ubuntu]" > inventory.ini
      #     echo "localhost ansible_connection=ssh ansible_user=${{ secrets.RPI5_USERNAME }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_port=2222" >> inventory.ini
      #     echo "Contents of the inventory file:"
      #     cat inventory.ini  # Debugging: show the contents of the inventory file

      # - name: Run Ansible Playbook
      #   run: |
      #     echo "Running Ansible playbook..."
      #     ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i inventory.ini ansible/install_docker.yml
      #   env:
      #     ANSIBLE_USER: ${{ secrets.RPI5_USERNAME }}
      #     ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa
