name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH private key
        run: | 
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY_2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Add router public IP address to known hosts
        run: | 
          ssh-keyscan -H -p ${{ secrets.ROUTER_PORT }} ${{ secrets.ROUTER_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Test Router Connectivity
        run: |
          echo "Pinging the router..."
          ping -c 4 ${{ secrets.ROUTER_PUBLIC_IP }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "${{ secrets.ROUTER_PUBLIC_IP }}:${{ secrets.ROUTER_PORT }}," ansible/install_docker.yml
        env: 
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_USER: ${{ secrets.RPI5_USERNAME }}
          ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa
