# name: CI Workflow

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-site:latest .
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-site:latest

#       - name: Create Ansible directory on VM
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             mkdir -p ~/ansible
#             chmod 755 ~/ansible

#       - name: Copy Ansible files to VM
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           source: 'ansible/*'
#           target: '~/'

#       - name: Set permissions for Ansible files
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             chmod 644 ~/ansible/install_docker.yml
#             chmod 644 ~/ansible/hosts.ini
#             chmod 755 ~/ansible

#       - name: Create hosts.ini dynamically on VM
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             echo "[ubuntu]" > ~/ansible/hosts.ini
#             echo "${{ secrets.DIGITALOCEAN_VM_IP }} ansible_ssh_user=${{ secrets.DIGITALOCEAN_VM_USERNAME }} ansible_ssh_private_key_file=~/.ssh/authorized_keys2" >> ~/ansible/hosts.ini
#             chmod 644 ~/ansible/hosts.ini
            
#       - name: Print Ansible Inventory
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             cat ~/ansible/hosts.ini

#       - name: Run Ansible playbook on VM to install Docker
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             ansible-playbook -i ~/ansible/hosts.ini ~/ansible/install_docker.yml

#       - name: Deploy Docker container
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.DIGITALOCEAN_VM_IP }}
#           username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
#           key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-site:latest
#             docker stop my-nginx-container || true
#             docker rm my-nginx-container || true
#             docker run -d --name my-nginx-container -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-site:latest

name: Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ${{ secrets.DIGITALOCEAN_VM_IP }}, -u ${{ secrets.DIGITALOCEAN_VM_USERNAME }} -e "ansible_python_interpreter=/usr/bin/python3" install_docker.yml

