name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH private key
        run: | 
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY_2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Add router public IP address to known hosts
        run: | 
          # ssh -N -L ${{secrets.ROUTER_PORT}}:${{secrets.RPI5_IP}}:${{secrets.PORT}} -p ${{ secrets.ROUTER_PORT }} ${{ secrets.RPI5_USERNAME }}@${{ secrets.ROUTER_PUBLIC_IP}} &
          # sleep 5
          ssh -N -L 2222:192.168.0.174:22 -p ${{ secrets.ROUTER_PORT }} ${{ secrets.RPI5_USERNAME }}@${{ secrets.ROUTER_PUBLIC_IP}} &
          sleep 5
          

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 localhost "echo Connection Successful"


      - name: Add Ansible Host Key
        run: |
          echo "[ubuntu]" > inventory.ini
          echo "localhost ansible_connection=ssh ansible_user=${{ secrets.RPI5_USERNAME }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_port=${{ secrets.ROUTER_PORT }}" >> inventory.ini

      - name: Debug Inventory File
        run: |
          cat inventory.ini
          echo "Contents of the inventory file: "
          cat inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini ansible/install_docker.yml
        env: 
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_USER: ${{ secrets.RPI5_USERNAME }}
          ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa
